services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.standard
    command: -f NodeDocker.toml
    volumes:
      - ${PWD}/node/NodeDocker.toml:/usr/opt/bonsol/NodeDocker.toml
      - ${PWD}/node_keypair.json:/usr/opt/bonsol/keys/signer.json
      - ${PWD}/images:/usr/opt/bonsol/risc0_images/
    ports:
      - 9000:9000
    restart: always
    depends_on:
      - solana
  solana:
    image: anzaxyz/agave:v2.0.13
    entrypoint: ["solana-test-validator", "--limit-ledger-size", "100000", "--bind-address", "0.0.0.0", "--rpc-pubsub-enable-block-subscription", "--bpf-program", "BoNsHRcyLLNdtnoDf8hiCNZpyehMC4FDMxs6NTxFi3ew", "/programs/bonsol.so", "--bpf-program", "exay1T7QqsJPNcwzMiWubR6vZnqrgM16jZRraHgqBGG", "/programs/callback_example.so"]
    volumes:
      - ${PWD}/target/deploy:/programs
    ports:
      - 8899:8899
      - 8900:8900
    
