---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bonsol-provernode.fullname" . }}
  labels:
    {{- include "bonsol-provernode.labels" . | nindent 4 }}
spec:
  type: ClusterIP  
  ports:
  - name: prometheus
    port: 9000
  selector:
    {{- include "bonsol-provernode.selectorLabels" . | nindent 4 }}
