risc0_image_folder = "../elf"

[transaction_sender_config]
  Rpc = { rpc_url = "http://localhost:8899" }
[signer_config]
  KeypairFile = { path = "../relaykp.json" }
[ingester_config]
  GrpcSub = { grpc_url = "http://localhost:8080" }