[package]
name = "bonsol-schema"
version = "0.0.1"
description = "Bonsol types, schema definitions"
authors = ["anagram build team"]
repository = "https://github.com/anagrambuild/bonsol"
license = "MIT"
edition = "2021"

[dependencies]
flatbuffers = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
